<a href="https://colab.research.google.com/github/ankit-thawal47/60-days-inference-engineering/blob/main/Day2/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Autograd is essential component of PyTorch, which enables, automatic differentiation calculation, which helps in calculation in backward propgation. As the function in neural networks are nested, when calculating backward propogation, we need to find the derivation of many partial derivatives and autograd makes it easy as it keeps them calculated

Autograd build a computation graph(DAG) internally, and it maintains all the operations performed on tensors which have required_grad=True. This graph is then traverse backwards, when we say y.backward() to compute the gradients "efficiently" using the chain rule.

In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
print(x)

tensor([0., 1., 2., 3.])


In [3]:
x.requires_grad_(True)
x.grad

In [4]:
y = 2 * torch.dot(x,x)
print(y)

tensor(28., grad_fn=<MulBackward0>)


In [5]:
y.backward()


In [6]:
x.grad

tensor([ 0.,  4.,  8., 12.])

### Mathematical Explanation of `y.backward()` and `x.grad`

Let's analyze the function you defined:

`x = torch.arange(4.0)` which means `x = [x_0, x_1, x_2, x_3] = [0.0, 1.0, 2.0, 3.0]`

The expression for `y` is `y = 2 * torch.dot(x, x)`.

First, let's expand `torch.dot(x, x)`:
`torch.dot(x, x) = x_0^2 + x_1^2 + x_2^2 + x_3^2`

So, `y` can be written as:
`y = 2 * (x_0^2 + x_1^2 + x_2^2 + x_3^2)`
`y = 2x_0^2 + 2x_1^2 + 2x_2^2 + 2x_3^2`

When you call `y.backward()`, PyTorch computes the gradient of `y` with respect to each element of `x` (since `x.requires_grad_(True)` was set). This means it calculates the partial derivatives `dy/dx_0`, `dy/dx_1`, `dy/dx_2`, and `dy/dx_3`.

Let's calculate these partial derivatives:

*   `dy/dx_0 = d/dx_0 (2x_0^2 + 2x_1^2 + 2x_2^2 + 2x_3^2) = 4x_0`
*   `dy/dx_1 = d/dx_1 (2x_0^2 + 2x_1^2 + 2x_2^2 + 2x_3^2) = 4x_1`
*   `dy/dx_2 = d/dx_2 (2x_0^2 + 2x_1^2 + 2x_2^2 + 2x_3^2) = 4x_2`
*   `dy/dx_3 = d/dx_3 (2x_0^2 + 2x_1^2 + 2x_2^2 + 2x_3^2) = 4x_3`

So, the gradient vector `x.grad` will be `[4x_0, 4x_1, 4x_2, 4x_3]`.

Given `x = [0.0, 1.0, 2.0, 3.0]`:

*   `4 * x_0 = 4 * 0.0 = 0.0`
*   `4 * x_1 = 4 * 1.0 = 4.0`
*   `4 * x_2 = 4 * 2.0 = 8.0`
*   `4 * x_3 = 4 * 3.0 = 12.0`

Therefore, `x.grad` should be `[0.0, 4.0, 8.0, 12.0]`, which matches the output you observed in the notebook.

In [2]:
# Let's re-verify the calculation with the actual values of x
import torch

x_values = torch.arange(4.0)

# Calculate the expected gradients manually
expected_grad = 4 * x_values

print(f"Original x values: {x_values}")
print(f"Manually calculated gradient (4*x): {expected_grad}")

Original x values: tensor([0., 1., 2., 3.])
Manually calculated gradient (4*x): tensor([ 0.,  4.,  8., 12.])


### More Complex Example for Gradient Derivation

Let's consider a new function `y`:

`x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)`

`y = ((x * 2).sum() + x.mean() * 5).pow(2)`

**Your task:**

1.  Expand the expression for `y` in terms of `x_0, x_1, x_2, x_3`.
2.  Calculate the partial derivatives `dy/dx_0`, `dy/dx_1`, `dy/dx_2`, `dy/dx_3`.
3.  Based on these partial derivatives, what do you expect `x.grad` to be?

Take your time to work through it! Once you are ready, I'll execute the `y.backward()` and `x.grad` cells to show the PyTorch result.

In [3]:
import torch

x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)

# Define the complex function (modified)
y = ((x * 2).sum() * 5).pow(2)

print(f"Initial x: {x}")
print(f"Value of y: {y}")

Initial x: tensor([1., 2., 3., 4.], requires_grad=True)
Value of y: 10000.0


In [4]:
# Execute this cell after you have derived the gradients manually.
y.backward()
print(f"x.grad: {x.grad}")

x.grad: tensor([2000., 2000., 2000., 2000.])


### New Gradient Derivation Challenge

Consider a new function `y` with `x` being a 4-element tensor:

`x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)`

`y = (x[0] * x[1] * x[2]) + (x.sum()).pow(2) + torch.log(x[3])`

**Your Task:**

1.  Expand the expression for `y` in terms of `x_0, x_1, x_2, x_3`.
2.  Calculate the partial derivatives `dy/dx_0`, `dy/dx_1`, `dy/dx_2`, and `dy/dx_3`.
3.  Based on these partial derivatives and the initial values of `x`, what do you expect the `x.grad` tensor to be?

Once you have your manual derivation, run the next two cells to compare your results with PyTorch's `x.grad`.

In [5]:
import torch

x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)

# Define the new complex function
y = (x[0] * x[1] * x[2]) + (x.sum()).pow(2) + torch.log(x[3])

print(f"Initial x: {x}")
print(f"Value of y: {y}")

Initial x: tensor([1., 2., 3., 4.], requires_grad=True)
Value of y: 107.38629150390625


In [6]:
# Run this cell after you have derived the gradients manually.
y.backward()
print(f"x.grad: {x.grad}")

x.grad: tensor([26.0000, 23.0000, 22.0000, 20.2500])
